routersploit/interpreter.py
Don't raise exception. Just exit.
=> Exit by pressing Ctrl+D

routersploit/utils.py
=> string.letters to string.ascii_letters

routersploit/modules/creds/http_form_bruteforce.py, routersploit/modules/creds/http_form_default.py
Hi!
I think we have to replace `login={{LOGIN}}` with `login={{USER}}`, because it's `{{USER}}` in code.
=> Update creds/http_form description

README.md
Tested this on a fresh install of Ubuntu 16.04 Desktop LTS
These were the only things I needed to do to get it up and running. Successfully completed an autopwn on 127.0.0.1
=> Ubuntu installation

routersploit/utils.py
=> Open file using with block

routersploit/wordlists/passwords.txt, routersploit/wordlists/usernames.txt
More information:
http://portforward.com/default_username_password/ZTE.htm
http://portforward.com/default_username_password/Huawei.htm
=> Update usernames & passwords

.gitignore, routersploit/interpreter.py, routersploit/test/test_completer.py, routersploit/test/test_interpreter.py
Add help menus and help command
Add exec feature to be kinda msfconsole-y
Edit check behavior to be a little clearer/more logical
=> Closes #85 and #30, add exec feature, edit check

routersploit/modules/exploits/belkin/auth_bypass.py, routersploit/modules/exploits/belkin/g_n150_password_disclosure.py
Added Belkin Auth Bypass exploit
Improved Belkin password disclosure exploit
=> New Belkin exploit

Dockerfile, README.md
Also adds a `run_docker.sh` for quick bootstrap.
=> Add Docker container

README.md
Made the english a bit more natural. Added a link to the License, too.
=> Copyedited README

routersploit/modules/exploits/technicolor/tc7200_password_disclosure_v2.py
I wasn't able to test it... :( Can be improved later.
=> TC7200 password disclosure : new firmware config file decryption

routersploit/modules/exploits/bhu/bhu_urouter_rce.py, routersploit/modules/scanners/bhu_scan.py
Implements a module to exploit BHU's RCE on their uRouter (see http://www.ioactive.com/pdfs/BHU-WiFi_uRouter-Security_Advisory_Final081716.pdf)
I didn't have the device to actually test it so instead, I created a quick python server to reproduce the behavior shown in the advisory linked above. It should work but if anyone has the device, it would be nice to try it for real.
=> BHU uRouter RCE exploit

routersploit/modules/exploits/dlink/dwl_3200ap_password_disclosure.py
Implements [#191](https://github.com/reverse-shell/routersploit/issues/191) 
_--- EDIT
resolves #191_
=> D-Link DWL3200AP pw disclosure module

routersploit/modules/exploits/netgear/multi_password_disclosure-201701.py
=> netgear multi devices password disclosure

routersploit/modules/scanners/autopwn.py
=> Adding scanner results - could not be verified

routersploit/modules/exploits/netgear/dgn2200_dnslookup_cgi_rce.py
Adding NETGEAR DGN2200v1/v2/v3/v4 - 'dnslookup.cgi' Remote Command Execution exploit.
Resolves #200
=> Netgear DGN2200 dnslookup.cgi RCE exploit

routersploit/modules/exploits/dlink/dir_645_815_rce.py, routersploit/shell.py
Adding echo reverse shell technique for D-Link Dir-645 & Dir-815 RCE exploit
=> D-Link Dir-645 & Dir-815 RCE echo reverse shell

routersploit/modules/exploits/miele/pg8528_path_traversal.py
=> Miele Professional PG 8528 Path Traversal

routersploit/modules/exploits/dlink/dvg_n5402sp_path_traversal.py
Fixes false positives for DLink DVG N5402SP Path Traversal exploit
=> Fixing false positive for DLink DVG N5402SP Path Traversal

routersploit/modules/exploits/cisco/catalyst_2960_rocem.py
=> Cisco Catalyst 2960 ROCEM RCE exploit

routersploit/modules/exploits/cisco/cisco_ios_http_authorization_bypass.py
Hello i added the old but classic exploit for the Cisco http ios authorization bug.
[http://www.cvedetails.com/cve/cve-2001-0537](url)
This exploit targets a special URL if http server is enabled in cisco router. If it is successful any command can be executed.
e.g http://10.0.0.1/level/99/exec/-/show/startup/config
Below is the output from my test in my home lab. A simple for loop is used to try
access levels from 16-99, when successful the command is executed and result is printed in console.
Please note i am beginner in python and github and i tried to stick on your style and template for this exploit.
```
rsf > use exploits/cisco/cisco_ios_http_authorization_bypass
rsf (Cisco IOS HTTP Unauthorized Administrative Access) > set target 10.0.0.1
[+] {'target': '10.0.0.1'}
rsf (Cisco IOS …
```
=> Cisco http ios authorization bypass

routersploit/modules/exploits/technicolor/tg784_authbypass.py
=> Technicolor TG784 Authentication Bypass

routersploit/modules/exploits/cameras/multi/jvc_vanderbilt_honeywell_path_traversal.py
=> JVC & Vanderbilt & Honeywell Path Traversal

routersploit/modules/exploits/cameras/honeywell/hicc_1100pt_password_disclosure.py
=> Honeywell IP-Camera HICC-1100PT - Credentials Disclosure

routersploit/wordlists/defaults.txt, routersploit/wordlists/passwords.txt, routersploit/wordlists/usernames.txt
=> Tenvis TH692 Outdoor P2P HD Waterproof IP Camera - Creds

routersploit/modules/exploits/cameras/videoiq/videoiq_camera_path_traversal.py
=> VideoIQ Camera - Path Traversal

routersploit/modules/exploits/cameras/brickcom/corp_network_cameras_conf_disclosure.py
=> Brickcom Corp Network Camera Configuration Disclosure

routersploit/modules/exploits/misc/asus/b1m_projector_rce.py
=> Asus B1M Projector RCE exploit

routersploit/modules/exploits/misc/wepresent/wipg1000_rce.py, routersploit/wordlists/passwords.txt
=> WePresent WiPG-1000 RCE

routersploit/modules/exploits/routers/asmax/ar_1004g_password_disclosure.py, routersploit/modules/exploits/routers/asmax/ar_804_gu_rce.py
Improving Asmax exploits:
- fixing typos
- adding info during exploitation
- adding validators
=> Improving Asmax exploits

routersploit/modules/exploits/cameras/grandstream/gxv3611hd_ip_camera_rce.py, routersploit/modules/exploits/routers/belkin/play_max_prce.py, routersploit/modules/exploits/routers/billion/5200w_rce.py, routersploit/modules/exploits/routers/cisco/catalyst_2960_rocem.py, routersploit/modules/exploits/routers/cisco/firepower_management60_rce.py, routersploit/modules/exploits/routers/dlink/dsp_w110_rce.py, routersploit/modules/exploits/routers/dlink/dwr_932b_backdoor.py, routersploit/modules/exploits/routers/fortinet/fortigate_os_backdoor.py, routersploit/modules/exploits/routers/huawei/hg630a_default_creds.py, routersploit/modules/exploits/routers/juniper/screenos_backdoor.py, routersploit/modules/exploits/routers/multi/ssh_auth_keys.py, routersploit/modules/exploits/routers/netgear/r7000_r6400_rce.py, routersploit/modules/exploits/routers/ubiquiti/airos_6_x.py, routersploit/modules/exploits/routers/zte/f609_config_disclosure.py, routersploit/modules/exploits/routers/zte/f6xx_default_root.py
Adding FTP,SSH,Telnet ports option and some validators.
=> FTP,SSH,Telnet ports option

README.md
Procediment to install on Centos 7
=> Install on Centos 7

routersploit/modules/creds/snmp_bruteforce.py
Make snmp_bruteforce support snmp v1
=> Make snmp_bruteforce support snmp v1

routersploit/utils/__init__.py
=> Make show info print customized data correct

routersploit/modules/exploits/routers/multi/rom0.py
=> rom-0 exploit : fix password extraction bug

routersploit/modules/exploits/cameras/brickcom/users_cgi_cred_disclosure.py
Module targets a vulnerability in the "users.cgi" script on several Brickcom devices.
For reference:
https://www.exploit-db.com/exploits/42588/
https://www.brickcom.com/news/productCERT_security_advisorie.php
=> Add new Brickcom CGI credential disclosure module

routersploit/test/test_exploits.py
Adds a small unit test for the Exploit options property.
=> Add unit test for Exploit options property

routersploit/modules/exploits/routers/dlink/multi_hedwig_cgi_exec.py
Re-PR'd this one https://github.com/reverse-shell/routersploit/pull/319. I do have some issues now with it, for some reason when following the change, the delivery no longer works. In addition, with the new payload changes and keeping the module as it is, it as well fails. Any suggestions?
=> DLINK Hedwig CGI BOF Exec

routersploit/modules/exploits/cameras/multi/dvr_creds_disclosure.py, tests/exploits/cameras/multi/test_dvr_creds_disclosure.py
=> Adding exploit for CVE-2018-9995 - DVR Creds Disclosure

routersploit/core/exploit/option.py, routersploit/core/tcp/tcp_client.py, routersploit/modules/exploits/generic/heartbleed.py
Resolves #193 
Module based/ported from metasploit
=> OpenSSL Heartbleed module

routersploit/core/ftp/ftp_client.py, routersploit/core/tcp/tcp_client.py, routersploit/modules/exploits/generic/heartbleed.py, routersploit/modules/exploits/routers/dlink/dsl_2750b_rce.py, routersploit/modules/exploits/routers/technicolor/tg784_authbypass.py
=> Fixing tg784_authbypass

routersploit/modules/exploits/routers/multi/gpon_home_gateway_rce.py, tests/exploits/routers/multi/test_gpon_home_gateway_rce.py
=> GPON Home Routers - Adding delay for retrieving results

routersploit/core/exploit/shell.py
=> Fixing reverse shell with nat

routersploit/core/exploit/shell.py
=> Fixing race condition - HTTP Server

routersploit/core/ftp/ftp_client.py, routersploit/core/ssh/ssh_client.py, routersploit/core/tcp/tcp_client.py, routersploit/core/telnet/telnet_client.py, routersploit/core/udp/udp_client.py, rsf.py
=> Fix telnet timeout

docs/modules/exploits/routers/dlink/dsl_2750b_rce.md
**READY**
This pull request adds documentation for D-Link DSL2750B RCE module
Check docs/modules/exploits/routers/dlink/dsl_2750b_rce.md
=> Adding documentation for D-Link DSL2750B RCE module

.github/PULL_REQUEST_TEMPLATE.md
**READY**
This PR improves Pull Request template.
1. Create new PR
=> Improving PR template

routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py, routersploit/modules/exploits/routers/cisco/catalyst_2960_rocem.py, routersploit/modules/exploits/routers/dlink/dir_300_645_815_upnp_rce.py, routersploit/modules/exploits/routers/dlink/dir_815_850l_rce.py, routersploit/modules/exploits/routers/dlink/dwr_932b_backdoor.py, routersploit/modules/exploits/routers/huawei/hg520_info_dislosure.py, routersploit/modules/exploits/routers/netcore/udp_53413_rce.py, tests/creds/routers/mikrotik/test_api_ros_default_creds.py
**READY**
This PR fixes multiple TCP and UDP based exploits.
=> TCP & UDP based exploits

routersploit/interpreter.py
**READY**
This PR bumps version to 3.1.0
=> Bump v3.1.0

routersploit/core/exploit/option.py, routersploit/core/ftp/ftp_client.py, routersploit/core/http/http_client.py, routersploit/core/snmp/snmp_client.py, routersploit/core/ssh/ssh_client.py, routersploit/core/tcp/tcp_client.py, routersploit/core/telnet/telnet_client.py, routersploit/core/udp/udp_client.py, routersploit/modules/creds/cameras/acti/webinterface_http_form_default_creds.py, routersploit/modules/creds/cameras/basler/webinterface_http_form_default_creds.py, routersploit/modules/creds/generic/ftp_bruteforce.py, routersploit/modules/creds/generic/ftp_default.py, routersploit/modules/creds/generic/http_basic_digest_bruteforce.py, routersploit/modules/creds/generic/http_basic_digest_default.py, routersploit/modules/creds/generic/snmp_bruteforce.py, routersploit/modules/creds/generic/ssh_bruteforce.py, routersploit/modules/creds/generic/ssh_default.py, routersploit/modules/creds/generic/telnet_bruteforce.py, routersploit/modules/creds/generic/telnet_default.py, routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py, routersploit/modules/creds/routers/pfsense/webinterface_http_form_default_creds.py, routersploit/modules/exploits/routers/cisco/firepower_management60_rce.py, routersploit/modules/exploits/routers/cisco/secure_acs_bypass.py, routersploit/modules/exploits/routers/ipfire/ipfire_oinkcode_rce.py, routersploit/modules/exploits/routers/thomson/twg849_info_disclosure.py, routersploit/modules/exploits/routers/ubiquiti/airos_6_x.py, routersploit/modules/exploits/routers/zyxel/zywall_usg_extract_hashes.py, routersploit/modules/generic/bluetooth/btle_scan.py, routersploit/modules/generic/bluetooth/btle_write.py, routersploit/modules/scanners/autopwn.py
**READY**
This PR fixes OptBool to work on True/False values instead of using strings.
2. `use creds/generic/ftp_default`
3. `set verbose false`
4. `run`
=> Fixing boolean options

routersploit/core/telnet/telnet_client.py
**READY**
This PR adds try exception block to telnet read until method.
=> Fixing telnet read until

setup.py
**IN DEVELOPMENT**
This PR adds python package configuration - setup.py
1. Run: `python3 -m venv venv`
2. Run: `source venv/bin/activate`
3. Run: `python3 -m pip install .`
4. Run: `./run.py`
=> Python package configuration - setuptools

routersploit/modules/exploits/generic/heartbleed.py
**READY**
This PR resolves #470 
2. `use exploits/generic/heartbleed`
4. `run`
=> Fixing heartbleed exploit

.github/ISSUE_TEMPLATE.md
**READY**
This PR adds "ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY" statement to issue template.
1. Add new issue
=> Fixing ISSUE TEMPLATE

routersploit/interpreter.py, setup.py
**READY**
This PR bumps version to 3.2.0
=> Bump v3.2.0

routersploit/interpreter.py, setup.py
**READY**
This PR bumps version to 3.3.0
=> Bump v3.3.0

routersploit/core/exploit/shell.py
**READY**
This PR resolves #491 issue.
2. Select and execute exploit
3. Get `cmd>` prompt
4. Execute `show payloads`
=> Fix: Show/Set Payloads issue

requirements-dev.txt, requirements.txt, setup.py
**READY**
This PR switches from pycrypto to pycryptodome. It resolves #450 
1. Set up new environment
2. `python3 -m pip install -r requirements-dev.txt`
3. `make tests`
=> Switching to pycryptodome

routersploit/modules/exploits/routers/billion/billion_5200w_rce.py, routersploit/modules/exploits/routers/cisco/catalyst_2960_rocem.py, routersploit/modules/exploits/routers/cisco/firepower_management60_rce.py, routersploit/modules/exploits/routers/dlink/dir_815_850l_rce.py, routersploit/modules/exploits/routers/multi/tcp_32764_rce.py, routersploit/modules/exploits/routers/ubiquiti/airos_6_x.py, tests/exploits/routers/multi/test_tcp_32764_rce.py
**READY**
This PR fixes issues with multiple modules. This PR resolves #512 
2. `use exploits/routers/multi/tcp_32764_rce`
4. `run`
=> Fixing multiple modules

routersploit/core/exploit/option.py, routersploit/interpreter.py, routersploit/modules/payloads/perl/bind_tcp.py, routersploit/modules/payloads/perl/reverse_tcp.py, routersploit/modules/payloads/php/bind_tcp.py, routersploit/modules/payloads/php/reverse_tcp.py, routersploit/modules/payloads/python/bind_tcp.py, routersploit/modules/payloads/python/bind_udp.py, routersploit/modules/payloads/python/reverse_tcp.py, routersploit/modules/payloads/python/reverse_udp.py, tests/core/test_option.py
**READY**
This PR fixes options. It also adds test coverage for options.
2. `use scanner/autopwn`
4. set all options
5. `run`
=> Fixing options

routersploit/core/exploit/utils.py
**READY**
This PR fixes use command issue. Resolves #514 
2. `use exploits/routers/mikrotik`
=> Fixing use command issue

routersploit/modules/exploits/cameras/cisco/video_surv_path_traversal.py, tests/exploits/cameras/cisco/test_video_surv_path_traversal.py
**READY**
This PR adds tests for Cisco Video Surveillance Path Traversal module
1. Run `pytest tests/exploits/cameras/cisco/test_video_surv_path_traversal.py`
=> Adding tests for Cisco Video Surveillance Path Traversal module

tests/exploits/routers/billion/test_billion_5200w_rce.py
**READY**
This PR adds tests for Billion 5200W RCE module.
1. Execute `pytest tests/exploits/routers/billion/test_billion_5200w_rce.py`
=> Adding tests for Billion 5200W RCE module

tests/exploits/routers/cisco/test_firepower_management60_rce.py
**READY**
This PR adds tests for Firepower Management 6.0 RCE module.
1. Execute `pytest tests/exploits/routers/cisco/test_firepower_management60_rce.py`
=> Adding tests for Firepower Management 6.0 RCE

tests/exploits/routers/cisco/test_secure_acs_bypass.py
**READY**
This PR adds tests for Cisco Secure ACS Bypass module.
1. Execute `pytest tests/exploits/routers/cisco/test_secure_acs_bypass.py`
=> Adding tests for Cisco Secure ACS Bypass module

tests/exploits/routers/technicolor/test_tg784_authbypass.py
**READY**
This PR adds tests for Technicolor TG784 AuthBypass module.
1. Execute `pytest tests/exploits/routers/technicolor/test_tg784_authbypass.py`
=> Adding tests for Technicolor TG784 AuthBypass

routersploit/interpreter.py, setup.py
**READY**
This PR bumps version to 3.4.0
=> Bump v3.4.0

.travis/install.sh, requirements-dev.txt, routersploit/interpreter.py, tests/exploits/routers/dlink/test_dns_320l_327l_rce.py
**READY**
Fixes typos related to help.
1. run `./rsf.py -h`
=> Fixing help typos

routersploit/core/exploit/option.py, tests/core/test_option.py
**READY**
Make OptInteger handle value 0 and hex value.
=> Make OptInteger handle value 0 and hex value.

routersploit/modules/exploits/cameras/dlink/dcs_930l_932l_auth_bypass.py, routersploit/modules/exploits/generic/heartbleed.py
**READY**
This PR fixes PEP8 issues in two exploits.
=> Fix PEP8 issues

README.md
**READY**
This pull request adds Ubuntu 20.04 installation instruction.
=> Add Ubuntu 20.04 installation instruction

routersploit/resources/wordlists/defaults.txt, routersploit/resources/wordlists/passwords.txt, routersploit/resources/wordlists/usernames.txt
**READY**
This PR adds ZXHN H168N hardcoded ssh credentials. Resolves #654
=> Add ZXHN H168N hardcoded ssh creds

routersploit/modules/exploits/cameras/multi/P2P_wificam_rce.py
Please note Pierre also references this post for this vulnerability, and the other source also references this blogpost. 
I plan to contribute more to this project, with more meaningful PRs.
**READY**
=> Added author and reference for the RCE

routersploit/modules/exploits/cameras/multi/P2P_wificam_rce.py
**READY**
Fixes the info missing comma issue
=> fix info issue p2p wificam rce exploit

routersploit/libs/apiros/apiros_client.py, routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py
**READY**
Fixes Mikrotik RouterOS API to support all versions.
=> Fix Mikrotik RouterOS API creds module

routersploit/modules/exploits/routers/huawei/hg532_rce.py
**READY**
Fixes HG532 RCE exploit module by checking server header.
=> Fix HG532 RCE exploit module

routersploit/core/exploit/printer.py
**READY**
Fixes printer issue, clone of PR https://github.com/threat9/routersploit/pull/736
=> Fix printer

routersploit/modules/exploits/routers/netgear/rax30_rce.py
**READY**
Resolves https://github.com/threat9/routersploit/issues/821
=> Fix Netgear RAX30 exploit check

docs/modules/exploits/routers/cisco/rv320_command_injection.md, docs/modules/exploits/routers/dlink/dir_655_866_652_rce.md, routersploit/modules/exploits/routers/cisco/rv320_command_injection.py, routersploit/modules/exploits/routers/dlink/dir_655_866_652_rce.py, tests/exploits/routers/cisco/test_rv320_command_injection.py, tests/exploits/routers/dlink/test_dir_655_866_652_rce.py
**READY**
#627
#576
#628
5 years later
2. `use exploits/routers/dlink/dsl_2750b_rce`
4. `run`
5. ...
=> Second attempt

docs/modules/exploits/cameras/multi/cctv_dvr_rce.md, routersploit/modules/exploits/cameras/multi/cctv_dvr_rce.py, tests/exploits/cameras/multi/test_cctv_dvr_rce.py
**READY**
New module  #540
2. `use exploits/cameras/multi/cctv_dvr_rce.py`
4. `set connback 192.168.1.100:5555`
5. `run`
6. ...
=> exploit-db.com/exploits/39596

routersploit/modules/exploits/routers/lg/nas_3718.py
2. `use exploits/routers/lg/nas_3718`
4. `run`
5. ...
rsf > use exploits/routers/lg/nas_3718
rsf (LG_NAS_3718.510.a0_RCE) > set target 192.168.1.1
[+] target => 192.168.1.1
rsf (LG_NAS_3718.510.a0_RCE) > run
[*] Running module exploits/routers/lg/nas_3718...
=> exploit-db.com/exploits/45109

routersploit/modules/exploits/cameras/beward/n100_rce.py
2. `use exploits/cameras/beward/n100_rce`
4. `run`
5. ...
=> exploit-db.com/exploits/46319

docs/modules/exploits/cameras/acti/acm_5611_rce.md, routersploit/modules/exploits/cameras/acti/acm_5611_rce.py
2. `use exploits/cameras/acti/acm_5611_rce`
4. `run`
5. ...
=> Added new module ACTi-ACM-5611-Video

docs/modules/exploits/cameras/geuterbruck/efd_2250.md, routersploit/modules/exploits/cameras/geuterbruck/efd_2250.py
2. `use exploits/cameras/geuterbruck/efd_2250`
4. `run`
5. ...
=> exploit-db.com/exploits/44957

routersploit/modules/exploits/cameras/multi/cctv_dvr_rce.py
=> Fix #854 missing re module import

requirements.txt, routersploit/core/snmp/snmp_client.py
**READY**
Use of a new pysnmp version.
Fixes: https://github.com/threat9/routersploit/issues/863, https://github.com/threat9/routersploit/issues/819
=> Switch to the new pysnmp version

Dockerfile
**READY**
Upgrades docker to python 3.9
=> Upgrade docker python to 3.9

setup.py
**READY**
Adds minimum python version to 3.9
=> Add minimum version of python to 3.9

routersploit/modules/exploits/cameras/geuterbruck/efd_2250.py, routersploit/modules/exploits/cameras/multi/cctv_dvr_rce.py
The last change request broke things if the request was None. Just patched that.
=> Handle None properly
